services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: ./docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
        PUID: ${PUID}
        PGID: ${PGID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}