services:
  php:
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: ./docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
        PUID: ${PUID}
        PGID: ${PGID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORKDIR: ${WORKDIR}
      XDEBUG_CONFIG: remote_host={{YOUR_IP_ADDRESS}}
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./:${WORKDIR}

  nginx:
    container_name: nginx_${PROJECT_NAME}
    image: nginx:1.19-alpine
    environment:
      WORKDIR: ${WORKDIR}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/configs/nginx/project.conf.template:/etc/nginx/templates/project.conf.template
      - ./var/log/nginx:/var/log/nginx
